import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useForm } from "react-hook-form";
import { Sparkles, Zap, ChevronRight } from "lucide-react";
import toast from "react-hot-toast";
import api from "../../utils/api";
import PageHeader from "../../components/ui/PageHeader";

const businessTypes = [
  "E-commerce Store", "School / College", "Restaurant / Cafe",
  "Retail Shop", "Healthcare / Clinic", "Real Estate Agency",
  "Salon / Spa", "Gym / Fitness Centre", "Travel Agency",
  "Tech Startup", "NGO / Non-profit", "Portfolio / Personal Brand", "Other",
];

const budgetRanges = [
  "₹10,000 – ₹25,000", "₹25,000 – ₹50,000",
  "₹50,000 – ₹1,00,000", "₹1,00,000 – ₹2,50,000",
  "₹2,50,000 – ₹5,00,000", "₹5,00,000+",
];

const timelines = [
  "1-2 weeks", "2-4 weeks", "1-2 months",
  "2-3 months", "3-6 months", "6+ months",
];

export default function ProposalGenerator() {
  const navigate = useNavigate();
  const [clients, setClients] = useState([]);
  const [projects, setProjects] = useState([]);
  const [generating, setGenerating] = useState(false);
  const [step, setStep] = useState(0);

  const steps = [
    "Connecting to Gemini AI...",
    "Analysing project requirements...",
    "Writing executive summary...",
    "Building pricing breakdown...",
    "Finalising proposal...",
  ];

  const { register, handleSubmit, watch, formState: { errors } } = useForm();
  const watchedClientId = watch("clientId");

  useEffect(() => {
    api.get("/api/clients").then(r => setClients(r.data.clients)).catch(() => {});
    api.get("/api/projects").then(r => setProjects(r.data.projects)).catch(() => {});
  }, []);

  const filteredProjects = watchedClientId
    ? projects.filter(p => p.client?._id === watchedClientId || p.client === watchedClientId)
    : projects;

  const onSubmit = async (data) => {
    setGenerating(true);
    setStep(0);

    // Animate through steps while waiting
    const interval = setInterval(() => {
      setStep(s => (s < steps.length - 1 ? s + 1 : s));
    }, 1800);

    try {
      const selectedClient = clients.find(c => c._id === data.clientId);
      const payload = {
        clientId: data.clientId,
        projectId: data.projectId || undefined,
        title: `${selectedClient?.name || "Client"} — ${data.businessType} Proposal`,
        clientName: selectedClient?.name || data.clientName,
        businessType: data.businessType,
        scope: data.scope,
        budget: data.budget,
        timeline: data.timeline,
      };
      const res = await api.post("/api/proposals/generate", payload);
      clearInterval(interval);
      toast.success("Proposal generated by Gemini AI! 🎉");
      navigate(`/proposals/${res.data.proposal._id}`);
    } catch (err) {
      clearInterval(interval);
      toast.error(err.response?.data?.message || "AI generation failed. Check your Gemini API key.");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="animate-fade-in max-w-2xl">
      <PageHeader
        title="Generate Proposal"
        subtitle="Let Gemini AI write a professional proposal for your client"
        backTo="/proposals"
      />

      {/* AI Banner */}
      <div className="glass-card p-5 mb-6 border-violet-400/20 bg-gradient-to-r from-violet-400/5 to-teal-400/5">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-violet-400/10 border border-violet-400/20
            flex items-center justify-center flex-shrink-0">
            <Sparkles size={22} className="text-violet-400" />
          </div>
          <div>
            <h3 className="font-syne font-bold text-white text-sm">Powered by Google Gemini 1.5 Flash</h3>
            <p className="font-dm text-xs text-slate-400 mt-0.5">
              Fill in the details below and AI will generate a complete, professional proposal
              with executive summary, scope, timeline, pricing, and terms.
            </p>
          </div>
        </div>
      </div>

      {generating ? (
        <div className="glass-card p-12 flex flex-col items-center justify-center gap-6">
          <div className="relative">
            <div className="w-20 h-20 rounded-full border-2 border-violet-400/20 flex items-center justify-center">
              <Sparkles size={32} className="text-violet-400 animate-pulse" />
            </div>
            <div className="absolute inset-0 rounded-full border-2 border-transparent border-t-violet-400 animate-spin" />
          </div>
          <div className="text-center">
            <p className="font-syne font-bold text-white text-lg mb-2">Generating your proposal...</p>
            <p className="font-dm text-sm text-slate-400 animate-pulse">{steps[step]}</p>
          </div>
          <div className="flex gap-1.5">
            {steps.map((_, i) => (
              <div key={i} className={`h-1.5 rounded-full transition-all duration-500
                ${i <= step ? "w-6 bg-violet-400" : "w-1.5 bg-bg-border"}`} />
            ))}
          </div>
        </div>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
          {/* Client & Project */}
          <div className="glass-card p-6 space-y-4">
            <h2 className="section-title">Client Information</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="label">Client *</label>
                <select className={`input-field ${errors.clientId ? "border-red-500" : ""}`}
                  {...register("clientId", { required: "Select a client" })}>
                  <option value="">Select client...</option>
                  {clients.map(c => <option key={c._id} value={c._id}>{c.name}</option>)}
                </select>
                {errors.clientId && <p className="text-red-400 text-xs mt-1">{errors.clientId.message}</p>}
              </div>
              <div>
                <label className="label">Linked Project <span className="normal-case font-normal text-slate-500">(optional)</span></label>
                <select className="input-field" {...register("projectId")}>
                  <option value="">No project</option>
                  {filteredProjects.map(p => <option key={p._id} value={p._id}>{p.title}</option>)}
                </select>
              </div>
              <div>
                <label className="label">Business Type *</label>
                <select className={`input-field ${errors.businessType ? "border-red-500" : ""}`}
                  {...register("businessType", { required: "Required" })}>
                  <option value="">Select type...</option>
                  {businessTypes.map(t => <option key={t} value={t}>{t}</option>)}
                </select>
                {errors.businessType && <p className="text-red-400 text-xs mt-1">{errors.businessType.message}</p>}
              </div>
            </div>
          </div>

          {/* Project Details */}
          <div className="glass-card p-6 space-y-4">
            <h2 className="section-title">Project Details</h2>
            <div>
              <label className="label">Project Scope *</label>
              <textarea
                className={`input-field resize-none ${errors.scope ? "border-red-500" : ""}`}
                rows={4}
                placeholder="Describe what the client needs. E.g: A full e-commerce website with product catalog, shopping cart, payment gateway (Razorpay), order management, and admin dashboard. Mobile responsive design required."
                {...register("scope", { required: "Scope is required", minLength: { value: 30, message: "Describe in at least 30 characters" } })}
              />
              {errors.scope && <p className="text-red-400 text-xs mt-1">{errors.scope.message}</p>}
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="label">Budget Range *</label>
                <select className={`input-field ${errors.budget ? "border-red-500" : ""}`}
                  {...register("budget", { required: "Select a budget range" })}>
                  <option value="">Select range...</option>
                  {budgetRanges.map(b => <option key={b} value={b}>{b}</option>)}
                </select>
                {errors.budget && <p className="text-red-400 text-xs mt-1">{errors.budget.message}</p>}
              </div>
              <div>
                <label className="label">Timeline *</label>
                <select className={`input-field ${errors.timeline ? "border-red-500" : ""}`}
                  {...register("timeline", { required: "Select a timeline" })}>
                  <option value="">Select timeline...</option>
                  {timelines.map(t => <option key={t} value={t}>{t}</option>)}
                </select>
                {errors.timeline && <p className="text-red-400 text-xs mt-1">{errors.timeline.message}</p>}
              </div>
            </div>
          </div>

          <button type="submit"
            className="w-full btn-primary flex items-center justify-center gap-3 py-4 text-base">
            <Sparkles size={18} />
            Generate with Gemini AI
            <ChevronRight size={16} />
          </button>
        </form>
      )}
    </div>
  );
}
